// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gym-calm/History.tsx": () => import("../components/mockups/gym-calm/History.tsx"),
  "./components/mockups/gym-calm/Plans.tsx": () => import("../components/mockups/gym-calm/Plans.tsx"),
  "./components/mockups/gym-calm/Session.tsx": () => import("../components/mockups/gym-calm/Session.tsx"),
  "./components/mockups/gym-calm/Start.tsx": () => import("../components/mockups/gym-calm/Start.tsx"),
  "./components/mockups/gym-current/History.tsx": () => import("../components/mockups/gym-current/History.tsx"),
  "./components/mockups/gym-current/Plans.tsx": () => import("../components/mockups/gym-current/Plans.tsx"),
  "./components/mockups/gym-current/Session.tsx": () => import("../components/mockups/gym-current/Session.tsx"),
  "./components/mockups/gym-current/Start.tsx": () => import("../components/mockups/gym-current/Start.tsx"),
  "./components/mockups/gym-focus/History.tsx": () => import("../components/mockups/gym-focus/History.tsx"),
  "./components/mockups/gym-focus/Plans.tsx": () => import("../components/mockups/gym-focus/Plans.tsx"),
  "./components/mockups/gym-focus/Session.tsx": () => import("../components/mockups/gym-focus/Session.tsx"),
  "./components/mockups/gym-focus/Start.tsx": () => import("../components/mockups/gym-focus/Start.tsx"),
  "./components/mockups/gym-power/History.tsx": () => import("../components/mockups/gym-power/History.tsx"),
  "./components/mockups/gym-power/Plans.tsx": () => import("../components/mockups/gym-power/Plans.tsx"),
  "./components/mockups/gym-power/Session.tsx": () => import("../components/mockups/gym-power/Session.tsx"),
  "./components/mockups/gym-power/Start.tsx": () => import("../components/mockups/gym-power/Start.tsx")
};
